/**
 * NexusOps — FAQPage (Knowledge Center)
 * Route: /faq (public)
 *
 * Accordion-style FAQ with 18 questions grouped by category.
 * No auth required — serves as a pre-sales and support resource.
 */
import { useState } from "react";
import { ChevronDown, ChevronUp, Search, BookOpen, Shield, Zap, CreditCard, Users, Settings2 } from "lucide-react";
import { Link } from "wouter";

// ─── Types ────────────────────────────────────────────────────────────────────

type FAQItem = {
  q: string;
  a: string;
};

type FAQCategory = {
  id: string;
  label: string;
  icon: JSX.Element;
  items: FAQItem[];
};

// ─── Data ─────────────────────────────────────────────────────────────────────

const ICON_PROPS = { size: 16, strokeWidth: 1.75 };

const CATEGORIES: FAQCategory[] = [
  {
    id: "platform",
    label: "Platform & Features",
    icon: <BookOpen {...ICON_PROPS} />,
    items: [
      {
        q: "What is NexusOps?",
        a: "NexusOps is a runtime-independent AI agent governance platform built for marketing operations teams. It provides a unified control plane for orchestrating, monitoring, and auditing AI-driven automation workflows — regardless of whether they run on Make, n8n, or custom agents.",
      },
      {
        q: "Which automation runtimes does NexusOps support?",
        a: "NexusOps supports Make (Integromat), n8n, and any custom webhook-based agent. The platform is runtime-agnostic: workflows emit execution events via a standardised webhook, and NexusOps captures, traces, and governs them centrally.",
      },
      {
        q: "What is the Governance Health Score?",
        a: "The Governance Health Score (0–100) is a composite metric calculated from four dimensions: audit log completeness (40%), AI interaction traceability (30%), report approval rate (20%), and workflow reliability (10%). It gives teams a single at-a-glance indicator of their AI governance posture.",
      },
      {
        q: "Can I use NexusOps without connecting an external automation platform?",
        a: "Yes. NexusOps includes demo data seeding and a standalone dashboard that works out of the box. You can explore the full governance interface, AI logs, performance metrics, and reports before connecting any external runtime.",
      },
    ],
  },
  {
    id: "governance",
    label: "AI Governance",
    icon: <Shield {...ICON_PROPS} />,
    items: [
      {
        q: "How does NexusOps ensure AI decision traceability?",
        a: "Every AI interaction is logged with the model used, the prompt sent, the response received, token count, confidence score, and timestamp. These records are stored immutably and surfaced in the AI Interactions audit view, enabling full post-hoc review of every AI-assisted decision.",
      },
      {
        q: "What is the approval workflow for AI-generated reports?",
        a: "Reports generated by the system can be submitted for human review. Approvers can accept or reject a report with written justification. Approval rates feed directly into the Governance Health Score, incentivising teams to maintain active human oversight.",
      },
      {
        q: "Does NexusOps support role-based access control?",
        a: "Yes. The platform supports two roles out of the box: standard users and admins. Admins can access the system administration panel, manage integrations, run data syncs, and view all user accounts. Role-gated UI elements are hidden from non-admin users.",
      },
      {
        q: "Is audit log data tamper-proof?",
        a: "Execution logs are written to Supabase with append-only semantics and are not editable through the UI. For production deployments, Supabase Row Level Security (RLS) policies can be configured to prevent even admin-level updates, providing a tamper-evident audit trail.",
      },
    ],
  },
  {
    id: "integrations",
    label: "Integrations & Webhooks",
    icon: <Zap {...ICON_PROPS} />,
    items: [
      {
        q: "How do I connect Make or n8n to NexusOps?",
        a: "Add an HTTP module at the end of your Make/n8n workflow that POSTs a JSON payload to your NexusOps ingest webhook: POST /api/webhooks/ingest. Include fields such as workflow_id, step_name, status, runtime, and message. NexusOps verifies an HMAC-SHA256 signature if you configure the shared secret in Settings.",
      },
      {
        q: "What payload format does the webhook ingest endpoint expect?",
        a: 'The endpoint accepts any JSON object. Recognised fields include: workflow_id (string), step_name (string), status ("success" | "failed" | "skipped"), event_type (string), runtime (e.g. "make" | "n8n"), message (string), and timestamp (ISO 8601). Unknown fields are stored as metadata.',
      },
      {
        q: "Is the webhook endpoint secured?",
        a: "Yes. You can configure a shared secret in Settings → API & Webhooks. NexusOps will then verify the x-make-signature or x-n8n-signature header using HMAC-SHA256. Requests with an invalid or missing signature are rejected with HTTP 401.",
      },
    ],
  },
  {
    id: "billing",
    label: "Plans & Billing",
    icon: <CreditCard {...ICON_PROPS} />,
    items: [
      {
        q: "What's included in the free Starter plan?",
        a: "The Starter plan includes up to 3 active workflows, 1,000 execution log entries per month, the full governance dashboard, and community support. It is free forever with no credit card required.",
      },
      {
        q: "Can I switch plans at any time?",
        a: "Yes. Upgrades take effect immediately and you are charged a prorated amount for the remainder of the billing cycle. Downgrades take effect at the end of the current billing period. You can cancel at any time from Settings → Billing.",
      },
      {
        q: "Do you offer annual billing?",
        a: "Yes. Annual billing is available for the Pro plan at a 17% discount ($490/year vs $588/year monthly). Enterprise plans are billed annually by default. Contact sales@nexusops.io for custom pricing.",
      },
    ],
  },
  {
    id: "team",
    label: "Team & Collaboration",
    icon: <Users {...ICON_PROPS} />,
    items: [
      {
        q: "How do I invite team members?",
        a: "Go to Settings → Team and enter the email address of the person you want to invite. Choose their role (Member or Admin) and click Send Invite. They will receive an email with a sign-up link that pre-assigns them to your organisation.",
      },
      {
        q: "Can multiple team members approve reports simultaneously?",
        a: "Yes. Reports can be reviewed by any user with the Reviewer or Admin role. Multiple approvers can leave comments, but only one approval or rejection is required to change the report status. A full approval history is maintained for compliance purposes.",
      },
    ],
  },
  {
    id: "technical",
    label: "Technical & Security",
    icon: <Settings2 {...ICON_PROPS} />,
    items: [
      {
        q: "What technologies does NexusOps run on?",
        a: "NexusOps is built on React 19 (Vite, Tailwind), a Node.js/Express backend with tRPC v11, Supabase (PostgreSQL + auth), and Airtable for supporting governance data. It is deployed on Render and designed for zero-downtime, 12-factor compliance.",
      },
      {
        q: "Is my data stored in Europe or the US?",
        a: "By default, Supabase data is stored in the region you chose when creating your project. NexusOps does not mandate a specific region. Enterprise customers can request EU-only data residency. Airtable data is stored in the United States.",
      },
    ],
  },
];

// ─── Components ───────────────────────────────────────────────────────────────

function AccordionItem({ item, isOpen, onToggle }: { item: FAQItem; isOpen: boolean; onToggle: () => void }) {
  return (
    <div
      style={{
        borderBottom: "1px solid var(--color-border-subtle)",
      }}
    >
      <button
        onClick={onToggle}
        style={{
          width: "100%",
          display: "flex",
          alignItems: "flex-start",
          justifyContent: "space-between",
          gap: "1rem",
          padding: "1rem 0",
          background: "none",
          border: "none",
          cursor: "pointer",
          textAlign: "left",
        }}
      >
        <span
          style={{
            fontFamily: "var(--font-display)",
            fontWeight: 600,
            fontSize: "0.9375rem",
            color: isOpen ? "var(--color-brand)" : "var(--color-text-primary)",
            lineHeight: 1.4,
            transition: "color 0.15s",
          }}
        >
          {item.q}
        </span>
        <span style={{ flexShrink: 0, color: "var(--color-text-tertiary)", marginTop: 2 }}>
          {isOpen ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
        </span>
      </button>
      {isOpen && (
        <p
          style={{
            margin: "0 0 1rem",
            fontFamily: "var(--font-body)",
            fontSize: "0.9rem",
            color: "var(--color-text-secondary)",
            lineHeight: 1.7,
          }}
        >
          {item.a}
        </p>
      )}
    </div>
  );
}

function CategorySection({ cat, openKey, setOpenKey }: {
  cat: FAQCategory;
  openKey: string | null;
  setOpenKey: (k: string | null) => void;
}) {
  return (
    <div style={{ background: "var(--color-bg-surface)", border: "1px solid var(--color-border-subtle)", borderRadius: "var(--radius-lg)", padding: "var(--space-5)", marginBottom: "var(--space-4)" }}>
      <div style={{ display: "flex", alignItems: "center", gap: "0.5rem", marginBottom: "var(--space-3)" }}>
        <span style={{ color: "var(--color-brand)" }}>{cat.icon}</span>
        <h2 style={{ margin: 0, fontFamily: "var(--font-display)", fontWeight: 700, fontSize: "1rem", color: "var(--color-text-primary)" }}>
          {cat.label}
        </h2>
      </div>
      {cat.items.map((item, idx) => {
        const key = `${cat.id}-${idx}`;
        return (
          <AccordionItem
            key={key}
            item={item}
            isOpen={openKey === key}
            onToggle={() => setOpenKey(openKey === key ? null : key)}
          />
        );
      })}
    </div>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function FAQPage(): JSX.Element {
  const [openKey, setOpenKey] = useState<string | null>(null);
  const [query, setQuery] = useState("");

  const filtered = query.trim()
    ? CATEGORIES.map((cat) => ({
        ...cat,
        items: cat.items.filter(
          (i) =>
            i.q.toLowerCase().includes(query.toLowerCase()) ||
            i.a.toLowerCase().includes(query.toLowerCase())
        ),
      })).filter((cat) => cat.items.length > 0)
    : CATEGORIES;

  const totalQ = CATEGORIES.reduce((acc, c) => acc + c.items.length, 0);

  return (
    <div style={{ minHeight: "100vh", background: "var(--color-bg-base)" }}>
      {/* Nav bar */}
      <header
        style={{
          position: "sticky",
          top: 0,
          zIndex: 50,
          borderBottom: "1px solid var(--color-border-subtle)",
          background: "rgba(9,11,15,0.85)",
          backdropFilter: "blur(12px)",
          padding: "0 var(--space-6)",
          height: 60,
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
        }}
      >
        <Link href="/">
          <span style={{ fontFamily: "var(--font-display)", fontWeight: 800, fontSize: "1.125rem", color: "var(--color-brand)", cursor: "pointer" }}>
            NexusOps
          </span>
        </Link>
        <div style={{ display: "flex", gap: "1rem", alignItems: "center" }}>
          <Link href="/auth">
            <span style={{ fontFamily: "var(--font-display)", fontWeight: 600, fontSize: "0.875rem", color: "var(--color-text-secondary)", cursor: "pointer" }}>
              Sign in
            </span>
          </Link>
          <Link href="/auth?mode=signup">
            <span
              style={{
                fontFamily: "var(--font-display)",
                fontWeight: 700,
                fontSize: "0.875rem",
                color: "var(--color-bg-base)",
                background: "var(--color-brand)",
                padding: "0.375rem 0.875rem",
                borderRadius: "var(--radius-full)",
                cursor: "pointer",
              }}
            >
              Get started
            </span>
          </Link>
        </div>
      </header>

      <main style={{ maxWidth: 800, margin: "0 auto", padding: "var(--space-12) var(--space-6)" }}>
        {/* Hero */}
        <div style={{ textAlign: "center", marginBottom: "var(--space-10)" }}>
          <h1
            style={{
              fontFamily: "var(--font-display)",
              fontWeight: 800,
              fontSize: "clamp(1.75rem, 4vw, 2.5rem)",
              color: "var(--color-text-primary)",
              marginBottom: "var(--space-3)",
              lineHeight: 1.2,
            }}
          >
            Knowledge Centre
          </h1>
          <p style={{ fontFamily: "var(--font-body)", color: "var(--color-text-secondary)", fontSize: "1.0625rem", marginBottom: "var(--space-6)" }}>
            {totalQ} answers across {CATEGORIES.length} categories. Can't find what you need?{" "}
            <a href="mailto:support@nexusops.io" style={{ color: "var(--color-brand)", textDecoration: "none" }}>Contact support</a>
          </p>

          {/* Search */}
          <div style={{ position: "relative", maxWidth: 480, margin: "0 auto" }}>
            <Search size={16} style={{ position: "absolute", left: 14, top: "50%", transform: "translateY(-50%)", color: "var(--color-text-tertiary)", pointerEvents: "none" }} />
            <input
              type="search"
              placeholder="Search questions…"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              style={{
                width: "100%",
                padding: "0.625rem 0.875rem 0.625rem 2.5rem",
                background: "var(--color-bg-surface)",
                border: "1px solid var(--color-border-subtle)",
                borderRadius: "var(--radius-full)",
                color: "var(--color-text-primary)",
                fontFamily: "var(--font-body)",
                fontSize: "0.9rem",
                outline: "none",
                boxSizing: "border-box",
              }}
            />
          </div>
        </div>

        {/* Categories */}
        {filtered.length === 0 ? (
          <div style={{ textAlign: "center", padding: "var(--space-12)", color: "var(--color-text-tertiary)", fontFamily: "var(--font-display)" }}>
            No results for "{query}"
          </div>
        ) : (
          filtered.map((cat) => (
            <CategorySection
              key={cat.id}
              cat={cat}
              openKey={openKey}
              setOpenKey={setOpenKey}
            />
          ))
        )}

        {/* Footer CTA */}
        <div
          style={{
            marginTop: "var(--space-10)",
            padding: "var(--space-8)",
            background: "linear-gradient(135deg, rgba(61,255,160,0.08) 0%, rgba(0,212,255,0.06) 100%)",
            border: "1px solid var(--color-border-subtle)",
            borderRadius: "var(--radius-xl)",
            textAlign: "center",
          }}
        >
          <h3 style={{ fontFamily: "var(--font-display)", fontWeight: 700, color: "var(--color-text-primary)", marginBottom: "var(--space-2)" }}>
            Still have questions?
          </h3>
          <p style={{ fontFamily: "var(--font-body)", color: "var(--color-text-secondary)", marginBottom: "var(--space-4)", fontSize: "0.9375rem" }}>
            Our team typically responds within 2 business hours.
          </p>
          <a
            href="mailto:support@nexusops.io"
            style={{
              display: "inline-block",
              padding: "0.625rem 1.5rem",
              background: "var(--color-brand)",
              color: "var(--color-bg-base)",
              fontFamily: "var(--font-display)",
              fontWeight: 700,
              fontSize: "0.9375rem",
              borderRadius: "var(--radius-full)",
              textDecoration: "none",
            }}
          >
            Email support
          </a>
        </div>
      </main>
    </div>
  );
}
